#!/usr/bin/env node
/*---------------------------------------------------------------------------------------------
 *  run.mjs — run this samples repo's Playwright e2e against a local universe-editor.
 *
 *  The samples live OUTSIDE the universe-editor pnpm workspace, so (like the
 *  main repo's scripts/e2e/run-external-e2e.mjs) this runner is the seam that
 *  makes their e2e work anyway:
 *
 *    1. Resolve the universe-editor checkout via UNIVERSE_EDITOR_REPO (default
 *       ../universe-editor) and validate it has the built e2e harness.
 *    2. Write e2e/harness.local.mjs — a static `export * from <file:// harness
 *       dist>` bridge — so the config + every spec load the harness synchronously
 *       (top-level await in a spec breaks test.describe; require(esm) is disabled
 *       by Playwright's ESM loader — see e2e/harness.mjs).
 *    3. Resolve Playwright's CLI from the harness package (createRequire), so the
 *       process loads the SAME physical @playwright/test the harness dist resolves
 *       to — Playwright breaks if two copies load.
 *    4. Strip ELECTRON_RUN_AS_NODE (Claude Code's shell injects it, degrading
 *       Electron to plain Node which rejects Chromium flags).
 *    5. Freshen the editor + extension-host build (turbo), skipped when
 *       UNIVERSE_E2E_EDITOR_PREBUILT=1.
 *    6. Build each tested sample (node esbuild.config.mjs) so the suite never
 *       runs a stale bundle.
 *    7. Run Playwright; positional args select samples (samples/<name>, <name>).
 *--------------------------------------------------------------------------------------------*/

import { createRequire } from 'node:module'
import { spawnSync } from 'node:child_process'
import { existsSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const samplesRoot = resolve(__dirname, '../..')

function resolveEditorRepo() {
  const fromEnv = process.env.UNIVERSE_EDITOR_REPO
  const repoRoot = fromEnv ? resolve(fromEnv) : resolve(samplesRoot, '..', 'universe-editor')
  const harnessPkg = resolve(repoRoot, 'packages/e2e-harness/package.json')
  if (!existsSync(harnessPkg)) {
    console.error(`run: e2e harness not found at ${harnessPkg}`)
    console.error('set UNIVERSE_EDITOR_REPO to a built universe-editor checkout')
    process.exit(1)
  }
  return repoRoot
}

const repoRoot = resolveEditorRepo()

// Write the static bridge so config + specs import the harness synchronously.
const harnessDist = resolve(repoRoot, 'packages/e2e-harness/dist/index.js')
const bridgeUrl = pathToFileURL(harnessDist).href
writeFileSync(
  resolve(samplesRoot, 'e2e/harness.local.mjs'),
  `// generated by scripts/e2e/run.mjs — do not edit\nexport * from ${JSON.stringify(bridgeUrl)}\n`,
)

// Positional args name the samples to run (samples/<name>, <name>, or a spec path).
const sampleNames = process.argv.slice(2).map((arg) => {
  let a = arg.replace(/\\/g, '/')
  if (a.startsWith('samples/')) a = a.slice('samples/'.length)
  return a.split('/')[0]
})

const { ELECTRON_RUN_AS_NODE: _ignored, ...inheritedEnv } = process.env

// Single physical @playwright/test: resolve from the harness package, the same
// tree the harness dist resolves its @playwright/test from.
const require = createRequire(resolve(repoRoot, 'packages/e2e-harness/package.json'))
const playwrightCli = require.resolve('@playwright/test/cli')

function run(command, args, opts = {}) {
  const res = spawnSync(command, args, { stdio: 'inherit', ...opts })
  if (res.error) throw res.error
  return res.status ?? 1
}

// 1) Freshen the editor + extension-host build the suite cold-launches.
if (!process.env.UNIVERSE_E2E_EDITOR_PREBUILT) {
  const turbo = resolve(repoRoot, 'node_modules/turbo/bin/turbo')
  const status = run(
    process.execPath,
    [
      turbo,
      'run',
      'build',
      '--filter=@universe-editor/editor...',
      '--filter=@universe-editor/extension-host...',
    ],
    { env: inheritedEnv, cwd: repoRoot },
  )
  if (status !== 0) {
    console.error('run: editor/extension-host build failed')
    process.exit(status)
  }
}

// 2) Build each tested sample so the suite loads a fresh dist/.
for (const name of sampleNames) {
  const sampleDir = resolve(samplesRoot, 'samples', name)
  const config = resolve(sampleDir, 'esbuild.config.mjs')
  if (!existsSync(config)) {
    console.error(`run: no esbuild.config.mjs in samples/${name}`)
    process.exit(1)
  }
  const status = run(process.execPath, [config], { env: inheritedEnv, cwd: sampleDir })
  if (status !== 0) {
    console.error(`run: build failed for samples/${name}`)
    process.exit(status)
  }
}

// 3) Run Playwright. Positional filters match against paths RELATIVE to the
//    config's testDir (../samples), so each filter is the sample name anchored
//    to its e2e dir (regex-escaped): testMatch '**/e2e/*.spec.ts' then selects
//    every spec under that sample.
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const config = resolve(samplesRoot, 'e2e/playwright.config.ts')
const filters = sampleNames.map((n) => `${escapeRe(n)}/e2e`)
const status = run(process.execPath, [playwrightCli, 'test', '-c', config, ...filters], {
  env: { ...inheritedEnv, PLAYWRIGHT_FORCE_TTY: '0' },
  cwd: samplesRoot,
})
process.exit(status)
