/*---------------------------------------------------------------------------------------------
 *  harness.mjs — re-export the universe-editor e2e harness for this out-of-workspace repo.
 *
 *  Samples cannot depend on @universe-editor/e2e-harness (private, workspace-only)
 *  or @playwright/test directly, so every symbol is re-exported from the main
 *  repo's built dist. The wiring lives in ./harness.local.mjs — generated by
 *  scripts/e2e/run.mjs from UNIVERSE_EDITOR_REPO — and is a STATIC re-export:
 *  it must be synchronous, because a top-level `await import(...)` here would
 *  make every spec's module graph async and Playwright then rejects
 *  `test.describe()` as "from an async describe block". (`createRequire` won't
 *  do either — Playwright registers a custom ESM loader that disables
 *  require(esm).) Always run e2e via `npm run e2e`, which (re)writes the bridge.
 *--------------------------------------------------------------------------------------------*/

export * from './harness.local.mjs'
